---

- name: menambah repository PPA
  apt_repository: repo={{ php_repo }}

- name: mengupdate aplikasi
  apt: update_cache=yes

- name: menginstall php
  apt: pkg={{ item }} state=latest
  with_items: "{{ php_packages }}"
  register: phpinstalled
  notify:
    - start php7-fpm

- name: Set cgi.fix_pathinfo = 1
  when: phpinstalled|success
  replace:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: '^;cgi.fix_pathinfo=[0-1]'
    replace: 'cgi.fix_pathinfo=1'
    backup: yes
  notify:
    - restart php7-fpm
    - reload nginx

- name: instalasi php7.0 gagal
  when: phpinstalled|failed
  fail: msg="instalasi php7.0 gagal. coba liat logs"
